exclude external needs from the identifier regex check (useblocks#1099)
useblocks/sphinx-needs pull request #1108
Opened 2024-02-15 09:05 UTC by David-Le-Nir

fix for [#1099](https://github.com/useblocks/sphinx-needs/issues/1099)

2024-02-15 09:37 UTC, danwos requested changes
Thanks for the quick PR :+1: 

The change in `need.py` looks good, as well as the updated test case.

However, I think we need to clean this PR a little bit. :)

Version changes are introduced by a separate PR. Makes it easier to rewind single commits. So please remove this.

`.DS_Store` and `sphinxcontrib-needs.iml` are also not needed.
It's okay to add them to `.gitignore` if it simplifies your life.

And it would be also good to add a small line to `docs/changelog.rst` for a `2.1.0` release.

2024-02-15 09:46 UTC, danwos commented
Ohh and please ignore the failing pre-commit action.
Looks like a new mypy version finds much more now. I deal with this in a different PR and will merge this PR by hand.

2024-02-15 09:51 UTC, David-Le-Nir commented
> Version changes are introduced by a separate PR. Makes it easier to rewind single commits. So please remove this.
> 
> .DS_Store and sphinxcontrib-needs.iml are also not needed.
> It's okay to add them to .gitignore if it simplifies your life.
> 
> And it would be also good to add a small line to docs/changelog.rst for a 2.1.0 release.

yes, sorry, my CLI shortcuts are a bit too "shortcutting" ... I'll fix that
yes, for the changelog, I didn't know which version to set. Also should I update the pyproject.toml to set 2.1.0 for version ?

2024-02-15 10:10 UTC, danwos commented
No, we need to raise or better add the version just in the changelog.
All the other locations (pyproject.toml, needs.py, ...) will be done by a separate PR.

2024-02-15 10:12 UTC, danwos commented
I was asked by @chrisjsewell to hold this PR back for some time.
He may have some concerns but is sitting on a train right now.

2024-02-26 03:32 UTC, chrisjsewell requested changes
This is all good thanks, if you can apply the changes and fix the merge conflicts

2024-02-26 03:32 UTC, chrisjsewell commented on docs/changelog.rst
> +-----
```suggestion
Unreleased
----------
```

2024-02-26 03:32 UTC, chrisjsewell commented on sphinx_needs/api/need.py
>          raise NeedsInvalidException(f"Given ID '{need_id}' does not match configured regex '{needs_config.id_regex}'")
```suggestion
    if (
        needs_config.id_regex
        and not is_external
        and not re.match(needs_config.id_regex, need_id)
    ):
        raise NeedsInvalidException(
            f"Given ID '{need_id}' does not match configured regex '{needs_config.id_regex}'"
        )
```

2024-02-26 03:33 UTC, chrisjsewell commented on sphinx_needs/api/need.py
>          raise NeedsInvalidException(f"Given ID '{need_id}' does not match configured regex '{needs_config.id_regex}'")
or this will be done by running pre-commit

2024-02-26 08:09 UTC, chrisjsewell approved these changes
cheers

2024-02-26 09:12 UTC, danwos approved these changes

2024-02-26 09:12 UTC, merged