✨ Add `ndf` role
useblocks/sphinx-needs pull request #1269
Opened 2024-09-03 14:46 UTC by chrisjsewell

Currently based on top of #1266 

----

There are currently two ways to use dynamic functions within need directives:

1. ``[[copy("id")]]``; is problematic, because it does not adhere to the rst/myst syntax specification, and has already show to cause issues and be surprising to users (#1263)

2. `` :need_func:`[[copy("id")]]` `` is better but overly verbose

In this PR, I introduce a new role, which I believe should supersede both: `` :ndf:`copy("id")` ``
Here we take the entire content to be the function, as so do not require the `[[]]`

Note, one thing that the role approach cannot do, is to allow placeholders in URLs, e.g. `` `link <http://www.[[copy('id')]]>`_ ``
However, if this is truly required, then I believe we should introduce a new role specifically for that.

2024-09-17 06:22 UTC, ubmarco commented
Hi @chrisjsewell, thanks for this proposal.
As you said and as the past showed, the `[[ ]]` construct is brittle and breaks RST.
I like the role approach and also the name. Here are my answers:

- [x] do we agree this role should be added
- [x] do we agree on its name
- [x] do we agree this should deprecate `[[...]]` in content
  - [ ] do we need an additional role for URL links with placeholders
- [x] do we agree this should deprecate `need_func`

For the URL links I'm hesitant to add it without reported use case.
For `ndf` - can we somehow make sure that the name does not interfere with other extensions providing a role of the same name? `need_func` was certainly more scoped to SN.

2024-09-17 10:22 UTC, chrisjsewell commented
Yeh cheers

> can we somehow make sure that the name does not interfere

Eurgh, I would be very surprised if someone else was specifically using `ndf` 😅
Currently it will just override any existing role.
Happy to think of an even more specific name, but the idea was to make it not too verbose, similar to `np`

2024-09-17 10:40 UTC, ubmarco approved these changes
LGTM in general, docs and still deprecation missing, but can be done in an upcoming PR

2024-09-17 10:40 UTC, ubmarco commented on tests/doc_test/doc_dynamic_functions/index.rst
>          nested id also :need_func:`[[copy("id")]]`
if `need_func` is deprecated, please add a check for the warning in the test case

2024-09-17 13:38 UTC, danwos requested changes
I'm okay with the changes. Good work.

But as this is a not backward-compatible change, we should add the docs and a depreciation warning for need_fuc with this PR.

2024-09-17 13:41 UTC, chrisjsewell commented
> But as this is a not backward-compatible change

yep I was already about to add docs and deprecations 👍 , but just to note, this PR on its own is backwards compatible; it is just adding a new role

2024-09-18 06:46 UTC, danwos requested changes
Looks great. Thanks for the doc updates.

2024-09-18 06:46 UTC, danwos approved these changes

2024-09-18 07:23 UTC, ubmarco approved these changes
Nice work and good addition to SN.

2024-09-18 08:00 UTC, merged