initial customizable grids
useblocks/sphinx-needs pull request #614
Opened 2022-06-16 17:31 UTC by PhilipPartsch

try to implement #612

2022-06-16 17:44 UTC, PhilipPartsch commented on sphinx_needs/layout.py
> +                        #result = nodes.Text(text, text)#dead code?
I belive it is dead code and can be removed.

2022-06-16 17:44 UTC, PhilipPartsch commented on sphinx_needs/layout.py
> +            return line_ready
Here we now return in element with out lines_container (block). This leads to missing <span> elements in the ouput. Is this an issue?

2022-06-16 17:44 UTC, PhilipPartsch commented on sphinx_needs/layout.py
> +        if len(section_nodes) == 1:
Ugly, but currently functional. I can refactor it, if we have an working solution.

2022-06-16 17:44 UTC, PhilipPartsch commented on sphinx_needs/layout.py
> +                if "colspan" in c_v and "rowspan" in c_v:
At first I had a for loop to add all elemnts, but I have to decrease these by one, so it is easier understable for the "user". Overall I have to think about, what is better:
- forward everything, without checking
- copy the know attributes

2022-06-16 17:45 UTC, PhilipPartsch commented
Tests are failing, because they have to be adpated, becasue of breaking change.

2022-06-18 17:08 UTC, danieleades requested changes
use snake case for function names. A few missing type annotations as well

2022-06-18 17:08 UTC, danieleades commented on sphinx_needs/layout.py
> +def getgridsfromconfig(app: Sphinx,):# -> dict:
this should use proper type annotations, not a type comment

2022-06-18 17:08 UTC, danieleades commented on sphinx_needs/layout.py
>      def _replace_place_holder(self, data):
type annotations?

2022-06-18 17:08 UTC, danieleades commented on sphinx_needs/layout.py
> +    def content(self):
type annotations?

2022-06-18 17:08 UTC, danieleades commented on sphinx_needs/needs.py
> +def isattributeset(grid: {}, attributes: []) -> bool:
```suggestion
def is_attribute_set(grid: {}, attributes: []) -> bool:
```

also, missing type annotations

2022-06-18 17:10 UTC, danieleades commented on docs/conf.py
> +needs_grids = {
these are really complex, stringly-typed dictionaries. Is it possible to replace any of the dicts used in this PR with classes?

2023-08-04 07:45 UTC, danwos commented
I would like to close this PR, as nobody is working on it and it is out of any with master.
Any concerns?

2023-10-19 11:54 UTC, closed without merging