added directive needattribute
useblocks/sphinx-needs pull request #616
Opened 2022-06-17 23:51 UTC by PhilipPartsch

try to implment #613

2022-06-17 23:53 UTC, PhilipPartsch commented on sphinx_needs/layout.py
> +        if isuml:
uml part has to be shifted from needuml. It would be nice to refer to uml with <need id>.attibute.

2022-06-18 17:01 UTC, danieleades requested changes

2022-06-18 22:02 UTC, PhilipPartsch commented on pyproject.toml
> +  'sphinx_needs.directives.needattribute',
Thnaks for the hint, changed it.

2022-06-21 07:49 UTC, danwos commented
I like the idea of ``needattribute``, but this PR also contains changes to ``needuml``, which should not be part of this PR and makes things complicated.

We should concentrate on storing the data first. Then, in further PRs, we deal with using this data in some other directives.

For me also some parts are looking more use case specific and are not generic enough.
But I will make a quick review and add my notes :)

For next PRs it would be also a good idea to write down a small concept with some rest example code first. 
So we can discuss it and get on the same page.

2022-06-21 08:17 UTC, danwos requested changes
Puhh, in this PR is happening so much and a lot of new features are added.
But all with no concept description or use case discussion.

I really would like to see the following changes in separate issues:
- needattribute
- Refactoring needuml (what about needflow?)
- multiline support in meta-data / layouts
- uml support in meta data / layouts

Especially for uml-support I have some doubts and see different solutions to get specific use-cases done.

Don't get me wrong, I like most of the changes, but I'm somehow lost seeing the impact to different use cases.

BTW: Isn't ``needattribute`` somehow the little sister of ``needextend``.
Maybe we can combine them....

2022-06-21 09:39 UTC, PhilipPartsch commented on sphinx_needs/directives/needattribute.py
> +        title = self.arguments[0].strip() if self.arguments else None
I did not fought about his. I use the None normally to know about unset values and excpetion creation if need.

2022-06-21 09:41 UTC, PhilipPartsch commented on sphinx_needs/layout.py
> +        if isuml:
I implemented a protoype to provide an exmaple requested [here](https://github.com/useblocks/sphinxcontrib-needs/issues/613#issuecomment-1160583656)

2023-10-19 11:57 UTC, closed without merging