Added Jinja support for need content via the `jinja_content` option
useblocks/sphinx-needs pull request #678
Opened 2022-08-30 20:51 UTC by iSOLveIT

Tasks
- [ ] * Provide a need option (flag) to activate jinja-parsing for the content (this is need-specific)
- [ ] * Render the content with jinja

As the jinja context, the following should be available
* [needs_filter_data](https://sphinxcontrib-needs.readthedocs.io/en/latest/configuration.html#needs-filter-data)
* need-data (if possible, as rst-rendering is done very early)

This PR is a fix for issue #604.

2022-09-06 06:19 UTC, danwos requested changes
Looks great, thanks :+1: 

I'm only missing an entry in the changelog :)

2022-09-06 06:24 UTC, twodrops commented
Thanks for implementing this in short time.
Could you please take care of the documentation part I mentioned [here](https://github.com/useblocks/sphinx-needs/issues/604#issuecomment-1152239751), as part of this PR or a separate issue?

2022-09-06 06:34 UTC, iSOLveIT commented
Thanks. I will add it to the changelog and do the necessary changes.

2022-09-14 06:02 UTC, danwos approved these changes

2022-09-14 06:10 UTC, merged