Fix: 799 needflow: nested needs on same level throws PlantUML error
useblocks/sphinx-needs pull request #801
Opened 2022-11-18 22:16 UTC by PhilipPartsch

fix #799

2022-11-21 11:08 UTC, danwos requested changes
Thanks for the Fix :+1: 

Looks good to me. I only have one small question.

2022-11-21 20:25 UTC, PhilipPartsch commented on tests/doc_test/doc_needflow/conf.py
> +needs_build_json = True
Is been removed in the new verion

2022-11-21 20:25 UTC, PhilipPartsch commented on tests/doc_test/doc_needflow_incl_child_needs/conf.py
> +needs_build_json = True
Is been removed in the new version

2022-11-22 13:16 UTC, danwos approved these changes

2022-11-22 13:16 UTC, merged